/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.xemocode.demo;

/**
 *
 * @author Saif
 */
public class Cleaner extends javax.swing.JFrame {

    /**
     * Creates new form Cleaner
     */
    public Cleaner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton67 = new javax.swing.JButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jButton95 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jButton98 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jButton99 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(837, 1752));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton61.setText("Technological Service");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 88, -1, -1));

        jButton62.setText("Cleaner");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 88, -1, -1));

        jButton63.setText("Nurse");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 88, -1, -1));

        jButton64.setText("Maid");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 88, -1, -1));

        jButton65.setText("Plumbing");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 89, -1, 21));

        jButton66.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton66.setText("Log Out");
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 113, -1, 226));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 114, 252, 225));

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jTextArea13.setText("Name: Ahmed\nAge: 25\nProfession: Electricia\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane13.setViewportView(jTextArea13);

        jPanel2.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 345, 189, 95));

        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        jTextArea14.setText("Name: Ahmed Ali\nAge: 22\nProfession: Cleaner\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane14.setViewportView(jTextArea14);

        jPanel2.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 345, 200, 99));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 114, 267, 225));

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jTextArea15.setText("Name: Akbor Mia\nAge: 25\nProfession: Cleaner\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane15.setViewportView(jTextArea15);

        jPanel2.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 345, 189, 95));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user2.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 60, 60));

        jButton67.setBackground(new java.awt.Color(0, 153, 153));
        jButton67.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton67.setForeground(new java.awt.Color(255, 255, 255));
        jButton67.setText("Utility Service Provider");
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 740, 67));

        jToggleButton5.setText("Electrical Service");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 88, -1, -1));

        jButton95.setBackground(new java.awt.Color(102, 0, 102));
        jButton95.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton95.setForeground(new java.awt.Color(255, 255, 255));
        jButton95.setText("more");
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jButton86.setBackground(new java.awt.Color(204, 0, 0));
        jButton86.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton86.setForeground(new java.awt.Color(255, 255, 255));
        jButton86.setText("Hire Now");
        jPanel2.add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, 30));

        jButton96.setBackground(new java.awt.Color(102, 0, 102));
        jButton96.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton96.setForeground(new java.awt.Color(255, 255, 255));
        jButton96.setText("more");
        jButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton96ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        jButton87.setBackground(new java.awt.Color(204, 0, 0));
        jButton87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton87.setForeground(new java.awt.Color(255, 255, 255));
        jButton87.setText("Hire Now");
        jButton87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton87ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 100, -1));

        jButton97.setBackground(new java.awt.Color(102, 0, 102));
        jButton97.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton97.setForeground(new java.awt.Color(255, 255, 255));
        jButton97.setText("more");
        jButton97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton97ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        jButton88.setBackground(new java.awt.Color(204, 0, 0));
        jButton88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton88.setForeground(new java.awt.Color(255, 255, 255));
        jButton88.setText("Hire Now");
        jPanel2.add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 267, 225));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, 226));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 252, 225));

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jTextArea16.setText("Name: Ahmed Ali\nAge: 22\nProfession: Cleaner\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane16.setViewportView(jTextArea16);

        jPanel2.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 200, 99));

        jButton98.setBackground(new java.awt.Color(102, 0, 102));
        jButton98.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton98.setForeground(new java.awt.Color(255, 255, 255));
        jButton98.setText("more");
        jPanel2.add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 850, -1, -1));

        jButton89.setBackground(new java.awt.Color(204, 0, 0));
        jButton89.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton89.setForeground(new java.awt.Color(255, 255, 255));
        jButton89.setText("Hire Now");
        jPanel2.add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 850, -1, 30));

        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jTextArea17.setText("Name: Akbor Mia\nAge: 25\nProfession: Cleaner\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane17.setViewportView(jTextArea17);

        jPanel2.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 740, 189, 95));

        jButton99.setBackground(new java.awt.Color(102, 0, 102));
        jButton99.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton99.setForeground(new java.awt.Color(255, 255, 255));
        jButton99.setText("more");
        jButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton99ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 850, -1, -1));

        jButton90.setBackground(new java.awt.Color(204, 0, 0));
        jButton90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton90.setForeground(new java.awt.Color(255, 255, 255));
        jButton90.setText("Hire Now");
        jButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton90ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 850, 100, -1));

        jButton100.setBackground(new java.awt.Color(102, 0, 102));
        jButton100.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton100.setForeground(new java.awt.Color(255, 255, 255));
        jButton100.setText("more");
        jPanel2.add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 850, -1, -1));

        jButton91.setBackground(new java.awt.Color(204, 0, 0));
        jButton91.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton91.setForeground(new java.awt.Color(255, 255, 255));
        jButton91.setText("Hire Now");
        jPanel2.add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 850, -1, -1));

        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jTextArea18.setText("Name: Ahmed\nAge: 25\nProfession: Electricia\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane18.setViewportView(jTextArea18);

        jPanel2.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 740, 189, 95));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 900, 267, 225));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 900, -1, 226));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 252, 225));

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jTextArea19.setText("Name: Ahmed Ali\nAge: 22\nProfession: Cleaner\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane19.setViewportView(jTextArea19);

        jPanel2.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1130, 200, 99));

        jButton101.setBackground(new java.awt.Color(102, 0, 102));
        jButton101.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton101.setForeground(new java.awt.Color(255, 255, 255));
        jButton101.setText("more");
        jPanel2.add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1240, -1, -1));

        jButton102.setBackground(new java.awt.Color(204, 0, 0));
        jButton102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton102.setForeground(new java.awt.Color(255, 255, 255));
        jButton102.setText("Hire Now");
        jPanel2.add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1240, -1, 30));

        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        jTextArea20.setText("Name: Akbor Mia\nAge: 25\nProfession: Cleaner\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane20.setViewportView(jTextArea20);

        jPanel2.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1130, 189, 95));

        jButton103.setBackground(new java.awt.Color(102, 0, 102));
        jButton103.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton103.setForeground(new java.awt.Color(255, 255, 255));
        jButton103.setText("more");
        jButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton103ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1240, -1, -1));

        jButton104.setBackground(new java.awt.Color(204, 0, 0));
        jButton104.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton104.setForeground(new java.awt.Color(255, 255, 255));
        jButton104.setText("Hire Now");
        jButton104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton104ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1240, 100, -1));

        jButton105.setBackground(new java.awt.Color(102, 0, 102));
        jButton105.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton105.setForeground(new java.awt.Color(255, 255, 255));
        jButton105.setText("more");
        jPanel2.add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1240, -1, -1));

        jButton106.setBackground(new java.awt.Color(204, 0, 0));
        jButton106.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton106.setForeground(new java.awt.Color(255, 255, 255));
        jButton106.setText("Hire Now");
        jPanel2.add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1240, -1, -1));

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jTextArea21.setText("Name: Ahmed\nAge: 25\nProfession: Electricia\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane21.setViewportView(jTextArea21);

        jPanel2.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1130, 189, 95));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 1300, 267, 225));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1290, -1, 226));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/img.icons8_1.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1300, 252, 225));

        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        jTextArea22.setText("Name: Ahmed Ali\nAge: 22\nProfession: Cleaner\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane22.setViewportView(jTextArea22);

        jPanel2.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1530, 200, 99));

        jButton107.setBackground(new java.awt.Color(102, 0, 102));
        jButton107.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton107.setForeground(new java.awt.Color(255, 255, 255));
        jButton107.setText("more");
        jPanel2.add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1640, -1, -1));

        jButton108.setBackground(new java.awt.Color(204, 0, 0));
        jButton108.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton108.setForeground(new java.awt.Color(255, 255, 255));
        jButton108.setText("Hire Now");
        jPanel2.add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1640, -1, 30));

        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        jTextArea23.setText("Name: Akbor Mia\nAge: 25\nProfession: Cleaner\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane23.setViewportView(jTextArea23);

        jPanel2.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1530, 189, 95));

        jButton109.setBackground(new java.awt.Color(102, 0, 102));
        jButton109.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton109.setForeground(new java.awt.Color(255, 255, 255));
        jButton109.setText("more");
        jButton109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton109ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1640, -1, -1));

        jButton110.setBackground(new java.awt.Color(204, 0, 0));
        jButton110.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton110.setForeground(new java.awt.Color(255, 255, 255));
        jButton110.setText("Hire Now");
        jButton110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton110ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1640, 100, -1));

        jButton111.setBackground(new java.awt.Color(102, 0, 102));
        jButton111.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton111.setForeground(new java.awt.Color(255, 255, 255));
        jButton111.setText("more");
        jPanel2.add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1640, -1, -1));

        jButton112.setBackground(new java.awt.Color(204, 0, 0));
        jButton112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton112.setForeground(new java.awt.Color(255, 255, 255));
        jButton112.setText("Hire Now");
        jPanel2.add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1640, -1, -1));

        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        jTextArea24.setText("Name: Ahmed\nAge: 25\nProfession: Electricia\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane24.setViewportView(jTextArea24);

        jPanel2.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1530, 189, 95));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1720, 100, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1720, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1343, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        Tecnician obj = new Tecnician();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
        Cleaner obj = new Cleaner();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        // TODO add your handling code here:
        Nursing obj = new Nursing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        // TODO add your handling code here:
        Maid obj = new Maid();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
        Plumbing obj = new Plumbing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        // TODO add your handling code here:
        Log_In obj = new Log_In();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
        Index obj = new Index();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        electrisian obj = new electrisian();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton96ActionPerformed
        // TODO add your handling code here:
        WorkerProfile obj = new WorkerProfile();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton96ActionPerformed

    private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton87ActionPerformed

    private void jButton99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton99ActionPerformed

    private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton90ActionPerformed

    private void jButton103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton103ActionPerformed

    private void jButton104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton104ActionPerformed

    private void jButton109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton109ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton109ActionPerformed

    private void jButton110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton110ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton110ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cleaner obj = new Cleaner();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cleaner obj = new Cleaner();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
        // TODO add your handling code here:
        WorkerProfile obj = new WorkerProfile();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton95ActionPerformed

    private void jButton97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton97ActionPerformed
        // TODO add your handling code here:
        WorkerProfile obj = new WorkerProfile();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton97ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cleaner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
